baseURL = "https://ghost062591.github.io/frostlabs-site"
languageCode = "en"
title = "FrostLabs"
theme = "blowfish"

enableRobotsTXT = true
summaryLength = 30

[pagination]
  pagerSize = 20

[outputs]
  home = ["HTML", "RSS", "JSON"]