baseURL = "https://ghost062591.github.io/frostlabs-site"
languageCode = "en"
title = "FrostLabs"
theme = "blowfish"

enableRobotsTXT = true
paginate = 20
summaryLength = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]