[goldmark]
  [goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    linkifyProtocol = 'https'
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = 'github'
    [goldmark.parser.attribute]
      block = true
      title = true
  [goldmark.renderer]
    hardWraps = false
    unsafe = true
    xhtml = false

[highlight]
  codeFences = true
  guessSyntax = true
  hl_Lines = ''
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = false
  style = 'github'
  tabWidth = 4

[tableOfContents]
  endLevel = 4
  ordered = false
  startLevel = 2